### ISSUE TITLE
[HELP] screen not turning off on Android

### ISSUE THREAD

**Issue by Faaatman** [jeremyko/flutter-proximity-sensor-plugin#1]
Hello, using the proximity sensor turns off the screen on an iOS physical device but it doesn't turn off the screen of an Android physical device.
How would I turn off the screen? is there are any permissions I'm missing or this package doesn't support that?
Thanks!

**Comment by KonKri** [comment]
I'm having the same problem. As a matter of fact, I'm testing it on two devices both Samsung. One runs Android 10 and it works fine, and the other one runs Android 11 and it doesn't register at all.

**Comment by mazen930** [comment]
@Faaatman  @KonKri  How you are able to turn screen off ? Can you provide me with the line or code that do that , 
also does it work for android and IOS ?
