### ISSUE TITLE
Need to declare as Health App in playstore?

### ISSUE THREAD

**Issue by kevinZartek** [jeremyko/flutter-proximity-sensor-plugin#12]
Playstore is asking to remove the below two permissions,

Your app uses the following health permissions and must meet [Health apps policy requirements](https://support.google.com/googleplay/android-developer/answer/13996823). If you don't have any health features in your app, remove these permissions from your app's manifest.

android.permission.ACTIVITY_RECOGNITION

android.permission.BODY_SENSORS_BACKGROUND

**Comment by krille-chan** [comment]
@jeremyko hello, we have the same problem. While your package works really well this is unfortunately blocking our app from being pushed to production now. The issue has been closed without a response and the Pull Request doesn't seem to be merged we are unsure how to proceed from here. 🙏 Thank you so much

**Comment by krille-chan** [comment]
Probably found a workaround. In your flutter app's manifest, just add:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="your-app-id"
    xmlns:tools="http://schemas.android.com/tools">

<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" tools:node="remove"/>
```

so an override for the permission but also `xmlns:tools="http://schemas.android.com/tools"` in the `manifest` object above. This should remove the permission from the app

**Comment by jeremyko** [comment]
hi. I removed that permission. Check out version 1.3.4.
