### ISSUE TITLE
Lower minSdkVersion to 23 to Support More Apps

### ISSUE THREAD

**Issue by oboard** [jeremyko/flutter-proximity-sensor-plugin#17]
I would like to address a concern regarding the recent update of the proximity_sensor plugin, which raised the minSdkVersion to 31. This change could potentially impact a significant number of existing apps that have not yet migrated to this version.

Currently, many applications in the market are still targeting lower SDK versions, particularly those that are designed to support a wider range of devices. By raising the minimum SDK version to 31, it limits the accessibility and usability of this plugin for developers who need to maintain compatibility with older devices.

I kindly request that you consider lowering the minSdkVersion back to 23 (or even lower), which would allow more developers to utilize this plugin without being forced to update their applications’ target SDK versions.

Thank you for your understanding and for your work on this plugin!

**Comment by jeremyko** [comment]
hi, Thanks for your advice. In the new version 1.3.5 the minSdkVersion has been reverted to 23.
