### ISSUE TITLE
Android 11- Not registering proximity events

### ISSUE THREAD

**Issue by KonKri** [jeremyko/flutter-proximity-sensor-plugin#2]
I'm testing it on two devices both Samsung. One runs Android 10 and it works fine, and the other one runs Android 11 and it doesn't register at all.

**Comment by jeremyko** [comment]
When I googled it, many people are complaining of the same symptoms due to sensor problems after the Android 11 update. In my opinion, this is very likely a problem with the android 11 update rather than a source code problem.

**Comment by KonKri** [comment]
Thank you very much for replying! I've read the complaints too. But when I use the phone app, or messenger call, or viber call, the sensor does work. So my suspicion is that maybe it's a different native implementation, before pushing to EventChanel. I'd be grateful if you could take a look at it!

Thanks in advance!

**Comment by mb1shka** [comment]
> Thank you very much for replying! I've read the complaints too. But when I use the phone app, or messenger call, or viber call, the sensor does work. So my suspicion is that maybe it's a different native implementation, before pushing to EventChanel. I'd be grateful if you could take a look at it!
> 
> Thanks in advance!

Did you find a solution? I am facing the same problem now.

**Comment by jeremyko** [comment]
Android 12 and higher are required to specify an explicit value for android:exported
This is an example.

<activity
    android:exported="true"
    ....

Regarding permissions, you may need the following settings in your AndroidManifest.xml file:

<uses-permission android:name="android.hardware.sensor.proximity"/>
<uses-permission android:name="android.permission.BODY_SENSORS_BACKGROUND"/>
<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION"/>

Some recent devices use virtual proximity sensors. There are no physical sensors. I found it hard to trust the sensor information in this case.

I hope this helps.
