### ISSUE TITLE
PlatformException(error, Neither user nor current process has android.permission.WAKE_LOCK

### ISSUE THREAD

**Issue by famasf1** [jeremyko/flutter-proximity-sensor-plugin#7]
My debug console print this whenever i'm trying to access the proximity sensor.

════════ Exception caught by services library ══════════════════════════════════
PlatformException(error, Neither user 10539 nor current process has android.permission.WAKE_LOCK., null, null)
════════════════════════════════════════════════════════════════════════════════

It seems to have something to do with the [recent PR commits](https://github.com/jeremyko/flutter-proximity-sensor-plugin/pull/6) regarding wake/sleep screen when there are objects in front of the screen. And if i added the following line to my AndroidManifest.xml.

```<uses-permission android:name="android.permission.WAKE_LOCK"/>```

Now everytime something is going near my phone screen. The screen completely shut off. This is undesired for my app (My app is device checking app and one of the test simply want to test if the proximity sensor work as expected.) as i don't want my screen to turn off. Is there anyway i can do to prevent this from happening other than downgrade to older version?

**Additional Information** : My device is OPPO Reno 5 Pro 5G. Android 13.

**Comment by jeremyko** [comment]
In my current situation, it seems best to revert the PR. please wait.

**Comment by jeremyko** [comment]
Version 1.2.0 has been released (It has been reverted to 1.0.4).

**Comment by holzgeist** [comment]
I'll send a new PR with added documentation as mentioned in the original PR.

Regarding the screen turning off: This change merely mirrors the behavior on iOS.

One could add a configuration method on this plugin to enable/disable screen behavior on Android, but a quick search suggests that this is not possible on iOS
